export const CORONA_API_CALL_REQUEST  = "CORONA_API_CALL_REQUEST"
export const CORONA_API_CALL_SUCCESS  = "CORONA_API_CALL_SUCCESS"
export const CORONA_API_CALL_FAIL  = "CORONA_API_CALL_FAIL"

export const FILTER_CORONA_DATA = "FILTER_CORONA_DATA"

export const SAVE_DATA_LS = "SAVE_DATA_LS"