export const OPINION_API_CALL_REQUEST  = "OPINION_API_CALL_REQUEST"
export const OPINION_API_CALL_SUCCESS  = "OPINION_API_CALL_SUCCESS"
export const OPINION_API_CALL_FAIL  = "OPINION_API_CALL_FAIL"

export const FILTER_OPINION_DATA = "FILTER_OPINION_DATA"

export const SAVE_DATA_LS = "SAVE_DATA_LS"