export const FEATURES_API_CALL_REQUEST  = "FEATURES_API_CALL_REQUEST"
export const FEATURES_API_CALL_SUCCESS  = "FEATURES_API_CALL_SUCCESS"
export const FEATURES_API_CALL_FAIL  = "FEATURES_API_CALL_FAIL"

export const FILTER_FEA_DATA = "FILTER_FEA_DATA"

export const SAVE_DATA_FEA_LS = "SAVE_DATA_FEA_LS"