export const ECONOMY_API_CALL_REQUEST  = "ECONOMY_API_CALL_REQUEST"
export const ECONOMY_API_CALL_SUCCESS  = "ECONOMY_API_CALL_SUCCESS"
export const ECONOMY_API_CALL_FAIL  = "ECONOMY_API_CALL_FAIL"

export const FILTER_ECO_DATA = "FILTER_ECO_DATA"

export const SAVE_DATA_LS = "SAVE_DATA_LS"